version: "3.8"

services:
  proxies-api:
    image: alexeynaidiuk/proxies-api:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "8182:8182"
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
