version: "3.8"

services:
#  proxy-parser:
#    image: alexeynaidiuk/proxy-parser:latest
#    volumes:
#      - ./proxies:/app/proxies
#      - ./sources:/app/sources
  proxies-api:
#    image: alexeynaidiuk/proxies-api:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "8182:8182"
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge